version: "3.7"
services:
  app:
      build:
        args:
          user: aji
          uid: 1000
        context: ./
        dockerfile: ./Dockerfile
      image: reward
      container_name: reward-app
      working_dir: /var/www/
      volumes:
        - ./:/var/www
        - ./user.ini:/usr/local/etc/php/php.ini
      networks:
        - reward
  nginx:
    image: nginx:1.17-alpine
    container_name: reward-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - reward
  rewarddb:
    image: mariadb:latest
    container_name: rewarddb
    ports:
      - 3306:3306
    volumes:
      - ./database:/database
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      reward:
        ipv4_address: 10.4.0.99
networks:
  reward:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.4.0.0/24
            gateway: 10.4.0.1
